---
title: "KKEMV II etapp venekeelne"
output: html_notebook
---

```{r}
tab = read.csv("https://github.com/carlmartinkeerberg/KKEMV-stat/raw/master/tabs/IIetapp_vene.csv",
               sep = ";",
               stringsAsFactors = F,
               header = F,
               encoding = "UTF-8",
               na.strings = "")
header = tab[2, c(1:ncol(tab)-1)]
tab = tab[c(3:nrow(tab)), c(1:ncol(tab)-1)]
names(tab) = header
```

```{r}
library(knitr)

r1_mean = rowMeans(data.matrix(tab[, c(3:5)]), na.rm = T)
r2_mean = rowMeans(data.matrix(tab[, c(6:8)]), na.rm = T)
r3_mean = rowMeans(data.matrix(tab[, c(9:11)]), na.rm = T)
r4_mean = rowMeans(data.matrix(tab[, c(12:14)]), na.rm = T)
r5_mean = rowMeans(data.matrix(tab[, c(15:17)]), na.rm = T)
total_mean = rowMeans(data.frame(r1_mean, r2_mean, r3_mean, r4_mean, r5_mean), na.rm = T)

diffs = data.frame(unlist(tab[, c(18:32)]), as.numeric(unlist(tab[, 3:17])) - total_mean)
names(diffs) = c("Kohtunik", "Erinevus")

diffs = aggregate(.~Kohtunik, diffs, mean)
diffs = diffs[order(diffs$Erinevus),]
rownames(diffs) = c()

kable(diffs, digits = 2)
```

```{r}
hist(total_mean,
     main = "Keskmised spiikripunktid",
     xlab = "Punktid",
     ylab = "Sagedus",
     xlim = c(60, 80),
     breaks = 6)

abline(v = mean(total_mean, na.rm = T),
       col = "blue",
       lwd = 2.5)

legend(73, 20,
       c("Aritm keskmine"),
       lwd = c(2.5),
       col = c("blue"))
```

```{r}
plot(c(mean(r1_mean, na.rm = T), mean(r2_mean, na.rm = T), mean(r3_mean, na.rm = T), mean(r4_mean, na.rm = T), mean(r5_mean, na.rm = T)),
     main = "Keskmised spiikripunktid läbi voorude",
     xlab = "Voor",
     ylab = "Punkte",
     ylim = c(66, 70),
     type = "b")
```
