---
title: "KKEMV I etapp"
output: html_notebook
---

```{r}
tab = read.csv("https://github.com/carlmartinkeerberg/KKEMV-stat/raw/master/Ietapp.csv",
               header = F,
               sep = ";",
               encoding = "UTF-8",
               dec = ".",
               stringsAsFactors = F)
```

```{r}
speakers = data.frame(tab[c(2:94),])
speakers_header = c(tab[c(1), ])
names(speakers) = speakers_header

alltotalavg = na.omit(as.numeric(speakers$TOTALAVG))

meantotalavg = mean(na.omit(as.numeric(speakers$TOTALAVG)))

hist(alltotalavg,
     main = "Keskmised spiikripunktid",
     xlab = "Punktid",
     ylab = "Sagedus",
     xlim = c(60, 80),
     breaks = 6)

abline(v = meantotalavg,
       col = "blue",
       lwd = 2.5)

legend(73, 20,
       c("Aritm keskmine"),
       lwd = c(2.5),
       col = c("blue"))
```

```{r}
totalspeakers = na.omit(data.frame(speakers$SPEAKER, as.numeric(speakers$TOTALAVG)))

bestspeaker = totalspeakers[which.max(totalspeakers$as.numeric.speakers.TOTALAVG.),]

print(bestspeaker)
```

```{r}
teams = data.frame(tab[c(96:125), c(1:27)])
teams_header = c(tab[c(64), c(1:27)])
names(teams) = teams_header
```

```{r}
r1 = mean(na.omit(as.numeric(speakers$R1AVG)))
r2 = mean(na.omit(as.numeric(speakers$R2AVG)))
r3 = mean(na.omit(as.numeric(speakers$R3AVG)))
r4 = mean(na.omit(as.numeric(speakers$R4AVG)))
r5 = mean(na.omit(as.numeric(speakers$R5AVG)))

avg = c(r1, r2, r3, r4, r5)

plot(avg,
     main = "Keskmised spiikripunktid läbi voorude",
     xlab = "Voor",
     ylab = "Punkte",
     ylim = c(68, 72),
     type = "b")
```

