---
title: "KKEMV II etapp"
output:
  html_document:
    df_print: paged
---
```{r}
tab = read.csv("https://github.com/carlmartinkeerberg/KKEMV-stat/raw/master/IIetapp.csv",
               header = F,
               sep = ";",
               encoding = "UTF-8",
               dec = ".",
               stringsAsFactors = F)
```

```{r}
speakers = data.frame(tab[c(2:63),])
names(speakers) = c(tab[c(1), ])
```

```{r}
teams = data.frame(tab[c(65:82), c(1:27)])
names(teams) = c(tab[c(64), c(1:27)])
```

```{r}
judges = data.frame(tab[c(84:106), c(1:21)])
names(judges) = c(tab[c(83), c(1:21)])
```

```{r}
totalspeakers = na.omit(data.frame(speakers$SPEAKER, as.numeric(speakers$TOTALAVG)))

bestspeaker = totalspeakers[which.max(totalspeakers$as.numeric.speakers.TOTALAVG.),]

print(bestspeaker)
```

```{r}
alltotalavg = na.omit(as.numeric(speakers$TOTALAVG))

meantotalavg = mean(na.omit(as.numeric(speakers$TOTALAVG)))

hist(alltotalavg,
     main = "Keskmised spiikripunktid",
     xlab = "Punktid",
     ylab = "Sagedus",
     xlim = c(60, 80),
     breaks = 6)

abline(v = meantotalavg,
       col = "blue",
       lwd = 2.5)

legend(73, 20,
       c("Aritm keskmine"),
       lwd = c(2.5),
       col = c("blue"))
```

```{r}
r1_ms = mean(na.omit(as.numeric(speakers$R1AVG)))
r2_ms = mean(na.omit(as.numeric(speakers$R2AVG)))
r3_ms = mean(na.omit(as.numeric(speakers$R3AVG)))
r4_ms = mean(na.omit(as.numeric(speakers$R4AVG)))
r5_ms = mean(na.omit(as.numeric(speakers$R5AVG)))

mean_speakers = c(r1_ms, r2_ms, r3_ms, r4_ms, r5_ms)

plot(mean_speakers,
     main = "Keskmised spiikripunktid läbi voorude",
     xlab = "Voor",
     ylab = "Punkte",
     ylim = c(68, 72),
     type = "b")
```

```{r}
judge_mean = data.frame(judges$JUDGE,
                        as.numeric(judges$R1P),
                        as.numeric(judges$R1O),
                        as.numeric(judges$R2P),
                        as.numeric(judges$R2O),
                        as.numeric(judges$R3P),
                        as.numeric(judges$R3O),
                        as.numeric(judges$R4P),
                        as.numeric(judges$R4O),
                        as.numeric(judges$R5P),
                        as.numeric(judges$R5O))

speaker_mean = data.frame(speakers$TEAM,
                          as.numeric(speakers$TOTALAVG))

team_mean = data.frame(aggregate(. ~ speakers.TEAM, speaker_mean, sum))

r1 = data.frame(judges$JUDGE, judges$R1PNAME, judges$R1P)
```

